channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - bumpversion
    - wheel
    - watchdog
    - flake8
    - tox
    - coverage
    - Sphinx
    - twine
    - pytest
    - pytest-runner
    - pytest-cov

